name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  gradle-build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle Wrapper JARs
        uses: gradle/wrapper-validation-action@v1
      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build --stacktrace